cask_args appdir: "/Applications"

# Tap additional repositories
tap "homebrew/cask-fonts"

# Command Line Tools
brew "circleci"
brew "coreutils"
brew "diff-so-fancy"
brew "gh"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "graphviz"
brew "imagemagick"
brew "node"
brew "nvm"
brew "pnpm"
brew "python"
brew "q"
brew "r"
brew "svn"
brew "watchman"
brew "zsh"

# Password Management
cask "1password"
cask "1password-cli"

# Productivity
cask "alfred"
cask "bartender"
cask "bitbar"
cask "breaktimer"
cask "cheatsheet"
cask "dropbox"
cask "fellow"
cask "grandperspective"
cask "notion"
cask "the-unarchiver"
cask "todoist"

# Communication
cask "discord"
cask "microsoft-teams"
cask "slack"

# Browsers
cask "google-chrome"

# Development
cask "docker"
cask "kitty"
cask "postman"
cask "stoplight-studio"
cask "sublime-merge"
cask "sublime-text"
cask "visual-studio-code"

# Design
cask "figma"
cask "sip"

# Media
cask "loopback"
cask "sonic-pi"
cask "spotify"
cask "transmission"
cask "vlc"

# Data Science
cask "r"
cask "rstudio"

# Window Management
cask "rectangle"
cask "spectacle"

# Fonts
cask "font-lato"
cask "font-merriweather"
cask "font-merriweather-sans"
cask "font-montserrat"
cask "font-open-sans"
cask "font-raleway"
cask "font-roboto"
cask "font-yeseva-one"
